language: python
python:
  - 2.7
install:
  - pip install .
  - pip install -r test-requirements.txt
  - pip list
script:
  - pep8 fastfood
  - flake8 fastfood
  - nosetests -c .nose
# The following line tells Travis CI to build in a container
sudo: false
